### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by kamzj** [iHelp101/XInsta#28]
For the past one week even after updating the hooks, Xinsta gives me the "download failed" error" What couls be the problem, i have even tries to downgrade both the Instagram and Xinsta app to no avail. Please help!!

**Comment by brato-mo** [comment]
Same here

**Comment by iHelp101** [comment]
XInsta 2.0.3 resolves this issue. Have you updated to it?

**Comment by kamzj** [comment]
Thank you, i will update it soon and give you feedback.

**Comment by brato-mo** [comment]
After restarting phone, its working now. Ty

**Comment by brato-mo** [comment]
When i try to download story, instagram stops responding.

**Comment by iHelp101** [comment]
Please provide your Xposed error log.

**Comment by brato-mo** [comment]
@iHelp101 how do i upload it and where

**Comment by brato-mo** [comment]
@iHelp101 
20180327_162700 - XInsta Initialized
20180327_162700 - Instagram Version Code: 99668514
20180327_162700 - Device Codename: HTC One M9
20180327_162700 - Android Version: 7.0
20180327_162700 - XInsta Version 2.0.3
20180327_162701 - Hooks Fetched!
20180327_162701 - Experimental Hooks Set
20180327_162703 - Pin Press New Touch Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180327_162703 - Pin Press New Touch Class - com.instagram.feed.p.a.en
20180327_162703 - Pin Press New Long Failed - java.lang.NoSuchMethodError: com.instagram.feed.p.a.em#run()#exact
20180327_162703 - Pin Press New Long Class - com.instagram.feed.p.a.em
20180327_162703 - Search Tag Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.t.b.c.b
20180327_162703 - Search Location Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.t.b.e.d
20180327_162703 - Search Username Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.t.a.c.b
20180327_162703 - Search Top Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.t.b.f.m
20180327_162703 - Story Privacy Hook Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.cz#Q()#exact
20180327_162703 - Story Privacy Hook Class - com.instagram.reels.fragment.cz
20180327_162703 - Story Privacy Hook Hook - Q
20180327_162703 - Forcing Media Class
20180327_162708 - Falling Back To New Video Method
20180327_162708 - Switch Link - Different Media Type
20180327_162717 - Unable To Determine Media - DS
20180327_162726 - ---------------------------
20180327_162726 - XInsta Initialized
20180327_162726 - Instagram Version Code: 99668514
20180327_162726 - Device Codename: HTC One M9
20180327_162726 - Android Version: 7.0
20180327_162726 - XInsta Version 2.0.3
20180327_162727 - Hooks Fetched!
20180327_162727 - Experimental Hooks Set
20180327_162729 - Pin Press New Touch Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180327_162729 - Pin Press New Touch Class - com.instagram.feed.p.a.en
20180327_162729 - Pin Press New Long Failed - java.lang.NoSuchMethodError: com.instagram.feed.p.a.em#run()#exact
20180327_162729 - Pin Press New Long Class - com.instagram.feed.p.a.em
20180327_162729 - Search Tag Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.t.b.c.b
20180327_162729 - Search Location Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.t.b.e.d
20180327_162729 - Search Username Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.t.a.c.b
20180327_162729 - Search Top Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.t.b.f.m
20180327_162729 - Story Privacy Hook Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.cz#Q()#exact
20180327_162729 - Story Privacy Hook Class - com.instagram.reels.fragment.cz
20180327_162729 - Story Privacy Hook Hook - Q
20180327_162729 - Forcing Media Class
20180327_162734 - Falling Back To New Video Method
20180327_162734 - Switch Link - Different Media Type
20180327_163114 - ---------------------------
20180327_163114 - XInsta Initialized
20180327_163114 - Instagram Version Code: 99668514
20180327_163114 - Device Codename: HTC One M9
20180327_163114 - Android Version: 7.0
20180327_163114 - XInsta Version 2.0.3
20180327_163114 - Hooks Fetched!
20180327_163115 - Experimental Hooks Set
20180327_163118 - Pin Press New Touch Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180327_163118 - Pin Press New Touch Class - com.instagram.feed.p.a.en
20180327_163118 - Pin Press New Long Failed - java.lang.NoSuchMethodError: com.instagram.feed.p.a.em#run()#exact
20180327_163118 - Pin Press New Long Class - com.instagram.feed.p.a.em
20180327_163118 - Search Tag Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.t.b.c.b
20180327_163118 - Search Location Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.t.b.e.d
20180327_163118 - Search Username Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.t.a.c.b
20180327_163118 - Search Top Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.t.b.f.m
20180327_163118 - Story Privacy Hook Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.cz#Q()#exact
20180327_163118 - Story Privacy Hook Class - com.instagram.reels.fragment.cz
20180327_163118 - Story Privacy Hook Hook - Q
20180327_163118 - Forcing Media Class
20180327_163119 - ---------------------------
20180327_163119 - XInsta Initialized
20180327_163119 - Instagram Version Code: 99668514
20180327_163119 - Device Codename: HTC One M9
20180327_163119 - Android Version: 7.0
20180327_163119 - XInsta Version 2.0.3
20180327_163119 - Hooks Fetched!
20180327_163120 - Experimental Hooks Set
20180327_163123 - Pin Press New Touch Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180327_163123 - Pin Press New Touch Class - com.instagram.feed.p.a.en
20180327_163123 - Pin Press New Long Failed - java.lang.NoSuchMethodError: com.instagram.feed.p.a.em#run()#exact
20180327_163123 - Pin Press New Long Class - com.instagram.feed.p.a.em
20180327_163123 - Search Tag Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.t.b.c.b
20180327_163123 - Search Location Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.t.b.e.d
20180327_163123 - Search Username Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.t.a.c.b
20180327_163123 - Search Top Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.t.b.f.m
20180327_163123 - Story Privacy Hook Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.cz#Q()#exact
20180327_163123 - Story Privacy Hook Class - com.instagram.reels.fragment.cz
20180327_163123 - Story Privacy Hook Hook - Q
20180327_163123 - Forcing Media Class
20180327_163124 - ---------------------------
20180327_163124 - XInsta Initialized
20180327_163124 - Instagram Version Code: 99668514
20180327_163124 - Device Codename: HTC One M9
20180327_163124 - Android Version: 7.0
20180327_163124 - XInsta Version 2.0.3
20180327_163125 - Hooks Fetched!
20180327_163125 - Experimental Hooks Set
20180327_163129 - Pin Press New Touch Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180327_163129 - Pin Press New Touch Class - com.instagram.feed.p.a.en
20180327_163129 - Pin Press New Long Failed - java.lang.NoSuchMethodError: com.instagram.feed.p.a.em#run()#exact
20180327_163129 - Pin Press New Long Class - com.instagram.feed.p.a.em
20180327_163129 - Search Tag Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.t.b.c.b
20180327_163129 - Search Location Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.t.b.e.d
20180327_163129 - Search Username Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.t.a.c.b
20180327_163129 - Search Top Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.t.b.f.m
20180327_163129 - Story Privacy Hook Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.cz#Q()#exact
20180327_163129 - Story Privacy Hook Class - com.instagram.reels.fragment.cz
20180327_163129 - Story Privacy Hook Hook - Q
20180327_163129 - Forcing Media Class
20180327_163542 - Falling Back To New Video Method
20180327_163542 - Switch Link - Different Media Type
20180327_163717 - ---------------------------
20180327_163717 - XInsta Initialized
20180327_163717 - Instagram Version Code: 99668514
20180327_163717 - Device Codename: HTC One M9
20180327_163717 - Android Version: 7.0
20180327_163717 - XInsta Version 2.0.3
20180327_163718 - Hooks Fetched!
20180327_163719 - Experimental Hooks Set
20180327_163722 - Pin Press New Touch Failed - java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
20180327_163722 - Pin Press New Touch Class - com.instagram.feed.p.a.en
20180327_163722 - Pin Press New Long Failed - java.lang.NoSuchMethodError: com.instagram.feed.p.a.em#run()#exact
20180327_163722 - Pin Press New Long Class - com.instagram.feed.p.a.em
20180327_163722 - Search Tag Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.t.b.c.b
20180327_163722 - Search Location Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.t.b.e.d
20180327_163722 - Search Username Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.t.a.c.b
20180327_163722 - Search Top Hook Failed - de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.instagram.t.b.f.m
20180327_163722 - Story Privacy Hook Failed - java.lang.NoSuchMethodError: com.instagram.reels.fragment.cz#Q()#exact
20180327_163722 - Story Privacy Hook Class - com.instagram.reels.fragment.cz
20180327_163722 - Story Privacy Hook Hook - Q
20180327_163722 - Forcing Media Class

**Comment by iHelp101** [comment]
I will work on updating the hooks for this new Instagram version shortly.

**Comment by iHelp101** [comment]
I updated the hooks for this version. Please reboot your device and everything should be working nicely again.

**Comment by brato-mo** [comment]
Its working. Thank you !

**Comment by kamzj** [comment]
Even after updating to the latest version, it still doesn't work.

**Comment by iHelp101** [comment]
Attach your Xposed error log please.

**Comment by kamzj** [comment]
My SuperSu has an error loggin activity for the current app don't know what
is the problem.

**Comment by iHelp101** [comment]
Please open Xposed -> Three Line Icon -> Logs. You can send the log to XInsta@ihelp101.com
